#日志记录
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

#mybatis配置
#mybatis:
#  #check-config-location: true
#  #executor-type: batch
#  type-aliases-package: com.nieyue.bean
#  com.nieyue.mapper-locations: classpath:config/com/nieyue/mapper/*.xml
#  configuration:
#    mapUnderscoreToCamelCase: true
#    useColumnLabel: true
#    useGeneratedKeys: true
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/com.nieyue.mapper/*Mapper.xml
  mapper-locations: classpath:/com/nieyue/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nieyue.bean
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.com.nieyue.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'


spring:
#  resources:
#    static-locations:  file:${myPugin.uploaderPath.rootPath}/, classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
#  jackson:
#    #property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone:  GMT+8
#      #generator:
#      #write-numbers-as-strings: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  session:
    store-type: redis
  profiles:
    active: dev
    #active: prod